# Site settings
title: tech.migge.io
long_title: Writing & Tech by Marc Dominik Migge
email: marc@migge.io
github_username: mdm
twitter_username: mdmigge
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Marc Dominik Migge. I'm a software developer from Cologne, Germany.
  This is where I write about tech and show off some projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tech.migge.io" # the base hostname & protocol for your site
defaults:
  -
    scope:
      path: ""
    values:
      math: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: article
      permalink: "/:year/:month/:day/:title/"
  -
    scope:
      path: "projects"
      type: "posts"
    values:
      layout: project
      permalink: "/projects/:title/"
# Build settings
markdown: kramdown
google_analytics: UA-68661393-1
